

BÀI 2. GIỚI THIỆU QUY TRÌNH PHÂN TÍCH SỐ LIỆU

# Làm sạch môi trường và load packages
```{r}
rm(list = ls())
library(pacman)
p_load(tidyverse, rio, here)

```


#B3 - Nhập dữ liệu
```{r}

# Cách 1:

df <- readRDS(file = "Dataset/covid_df.rds")

df1 <- read.csv("Dataset/covid_df.csv")

# Cách 2

df2 <- import(here("Dataset","covid_df.xlsx"))
df2 <- import(here("Dataset","covid_df.rds"))



# Xem dữ liệu 
View(df) # xem bo du lieu
names(df) # Xem ten cua cac bien

```

#B3 - Làm sạch dữ liệu 

```{r}

# Kiểm tra missing 
summary(.....)

df_miss <- import(here(....))
summary(....)
# Kiểm tra outliers trong dữ liệu total_cv_cases
hist(....)



# Kiểm tra định dạng của biến số
str(....)
## Kiểm tra định dạng của biến số dựa vào cửa sổ quản lý dữ liệu


# Nhóm lại các biến số
## mutate() và case_when()
## VD: Tao ra bien phan loai vaccine60 vs 2 nhom: vaccine >=60% va duoi < 60%

df_clean <- df %>% mutate(..... = case_when(  #Khong ghi de df de tien cho update cau lenh

))

# Tính toán lại biến số cv_case_10k = total_cv_cases/population*100000

```

#========================================
#========= BÀI TẬP THỰC HÀNH ============
#========================================

```{r}
# Q1. Nhập file dữ liệu excel: "covid_df_SeA.xlsx", luu ten file du lieu la "data"
library("pacman")
p_load(tidyverse, rio, here)
df <- import(here("dataset", "covid_df_SeA.xlsx"))

# Q2. Kiem tra du lieu "data". Co bao nhieu quoc gia duoc nhap vao?
view(df$location)#
# Q3. Kiem tra dinh dang cac bien so.
str(df)#


# Q4. # Kiểm tra missing. Bien so nao co missing va bao nhieu missing?
summary(df)

# Kiểm tra outliers trong dữ liệu
hist(df$total_cv_cases)
hist(df$total_cv_death)
hist(df$vax_per_100)
hist(df$fulvax_per_100)
hist(df$string_idx)
hist(df$population)
hist(df$population_density)
hist(df$aged_65_older)
hist(df$cardiovasc_death_rate)
hist(df$diabetes_prevalence)
hist(df$gdp_per_capita)

# Nhóm lại các biến số
## mutate() và case_when()
## VD: Tao ra bien phan loai quoc gia co so luong ca nhiem > 1 tr va <=1 tr
df_clean <- df %>% mutate(country_case = case_when(
  total_cv_cases > 1000000 ~ ">1000000", 
  total_cv_cases <= 1000000 ~ "<=1000000"))

# Tao ra bien so "death_case" = so luong ca tu vong trong 10000 ca nhiem 
df_clean <- df_clean %>% mutate(death_case = total_cv_death/total_cv_cases*10000)

# Lọc bộ dữ liệu
## Loc cac quoc gia voi so luong ca tu vong/10000 ca nhiem >10  va loai nuoc Timor ra khoi du lieu
view(df_clean)
df_clean_1 <- df_clean %>% filter(death_case >10)
view(df_clean_1)
df_clean_11 <- df_clean_1 %>% filter(location != "Timor")
View(df_clean_11)
## Loc lai bo du lieu voi cac cot gom: ten quoc gia, so ca tu vong, so ca nhiem, so luong ca tu vong/10000 ca nhiem
df_clean_3 <- df_clean %>% select(location, total_cv_death, total_cv_cases, death_case)
export(df_clean_3, here("dataset", "df_clean_Han_Apr8.rds"))
export(df_clean_1, here("dataset", "df_clean_Han_Apr8.rds"))
export(df_clean_11, here("dataset", "df_clean_Han_Apr8.rds"))
export(df_clean, here("dataset", "df_clean_Han_Apr8.rds"))

```
