

BÀI 2. GIỚI THIỆU QUY TRÌNH PHÂN TÍCH SỐ LIỆU

# Làm sạch môi trường và load packages
```{r}
rm(list = ls())
library(pacman)
p_load(tidyverse, rio, here)

```


#B3 - Nhập dữ liệu
```{r}

# Cách 1:

df <- readRDS(file = "Dataset/covid_df.rds")

df1 <- read.csv("Dataset/covid_df.csv")

###
df <- readRDS(file = "Dataset/covid_df.rds")
df <- readRDS(file = "Dataset/covid_df.rds")
df <- readRDS(file = "Dataset/covid_df.rds")

df <- read.csv("Dataset/covid_df.csv")
df <- read.csv("Dataset/covid_df.csv")


# Cách 2

df2 <- import(here("Dataset","covid_df.xlsx"))
df2 <- import(here("Dataset","covid_df.rds"))

###

df2 <- import(here("Dataset", "covid_df.xlsx"))
df2 <- import(here("Dataset", "covid_df.xlsx"))
df2 <- import(here("Dataset", "covid_df.xlsx"))

df2 <- import(here("Dataset", "covid_df.rds"))
df2 <- import(here("Dataset", "covid_df.rds"))

# Xem dữ liệu 
View(df) # xem bo du lieu
names(df) # Xem ten cua cac bien

```

#B3 - Làm sạch dữ liệu 

```{r}

# Kiểm tra missing 
summary(.....)

df_miss <- import(here(....))
summary(....)

###

df_miss <- import(here("Dataset", "covid_df_missing.xlsx"))
summary(df_miss)

b# Kiểm tra outliers trong dữ liệu total_cv_cases
hist(....)

### 
hist(df_miss$total_cv_cases)
hist(df$total_cv_cases)
df %>% ggplot(aes(x=total_cv_cases)) +
  geom_histogram()

# Kiểm tra định dạng của biến số
str(....)

str(df)
str(df$total_cv_cases)

## Kiểm tra định dạng của biến số dựa vào cửa sổ quản lý dữ liệu


# Nhóm lại các biến số
## mutate() và case_when()
## VD: Tao ra bien phan loai vaccine60 vs 2 nhom: vaccine >=60% va duoi < 60%

df_clean <- df %>% mutate(..... = case_when(  #Khong ghi de df de tien cho update cau lenh
  
))

df_clean <- df %>% mutate(vaccine60 = case_when(
  fulvax_per_100 >= 60 ~ ">=60",
  fulvax_per_100 <60 ~ "<60"
))
### kiem tra xem bien duoc tao chua
names(df_clean)

# Tính toán lại biến số cv_case_10k = total_cv_cases/population*100000

df_clean <- df_clean %>% mutate(.....)

df_clean <- df_clean %>% mutate(cv_case_10k = total_cv_cases/population*100000)

# Lọc bộ dữ liệu
## Lọc lại hàng  
df_clean <- df %>% filter(....)


df_clean1 <- df %>% filter(fulvax_per_100 >=60)
df_clean2 <- df %>% filter(vaccine60 == ">=60")

## Lọc lại cột 
df_clean_1 <- df_clean %>% select(....) #chon location,vaccine60, cv_case_10k

df_clean_2 <- df_clean %>% select(....) #xoa bo bieN total_cv_cases

df_clean_1 <- df_clean %>% select(location, vaccine60, cv_case_10k)

df_clean_2 <- df_clean %>% select(-total_cv_cases)
```

#B3. Xuat du lieu
```{r}

export(df_clean_2, here("Dataset", "df_clean_Nhi_Apr8.rds"))

export(df_clean_2, here("Dataset", "df_clean_Nhi_Apr8.xlsx"))
```


# ANSWER
```{r}

# Kiểm tra missing 
summary(df)

df_miss <- import(here("Dataset","covid_df_missing.xlsx"))
summary(df_miss)
# Kiểm tra outliers trong dữ liệu
hist(df$total_cv_cases)

df %>% ggplot(aes(x = total_cv_cases)) + 
  geom_histogram()

# Kiểm tra định dạng của biến số
str(df)
## Kiểm tra định dạng của biến số dựa vào cửa sổ quản lý dữ liệu


# Nhóm lại các biến số
## mutate() và case_when()
## VD: Tao ra bien phan loai vaccine >=60% va duoi < 60%

df_clean <- df %>% mutate(vaccine60 = case_when(  #Khong ghi de df de tien cho update cau lenh
   fulvax_per_100 < 60 ~ "<60%",
   fulvax_per_100 >= 60 ~ ">=60%"
))

# Tính toán lại biến số

df_clean <- df_clean %>% mutate(
  cv_case_10k = total_cv_cases/population*100000)

# Lọc bộ dữ liệu
## Lọc lại hàng 
df_clean <- df_clean %>% filter(cv_case_10k < 10000)

## Lọc lại cột 
df_clean_1 <- df_clean %>% select(location,vaccine60, cv_case_10k) #chon 
df_clean_2 <- df_clean %>% select(-total_cv_cases) #xoa bo bien.

```

# B3. Xuất dữ liệu
```{r}
export(df_clean_2, here("Dataset", "df_clean.rds"))
```



#========================================
#========= BÀI TẬP THỰC HÀNH ============
#========================================

```{r}
# Q1. Nhập file dữ liệu excel: "covid_df_SeA.xlsx", luu ten file du lieu la "data"

rm(list = ls())
data <- import(here("Dataset", "covid_df_SeA.xlsx"))

# Q2. Kiem tra du lieu "data". Co bao nhieu quoc gia duoc nhap vao?

view(data)

# Q3. Kiem tra dinh dang cac bien so. 

str(data)
str(data$iso_code)
str(data$location)


# Q4. # Kiểm tra missing. Bien so nao co missing va bao nhieu missing?

summary(data)


# Kiểm tra outliers trong dữ liệu

hist(data$total_cv_cases)
data %>% ggplot(aes(x=total_cv_cases)) +
  geom_histogram()

# Nhóm lại các biến số
## mutate() và case_when()
## VD: Tao ra bien phan loai quoc gia co so luong ca nhiem > 1 tr va <=1 tr

data_1 <- data %>% mutate(country_classification = case_when(
  total_cv_cases > 1000000 ~ ">1tr",
  total_cv_cases < 1000000 ~ "<1tr"
))
# Tao ra bien so "death_case" = so luong ca tu vong trong 10000 ca nhiem 

data_1 <- data_1 %>% mutate(death_case = total_cv_death/population*100000)

# Lọc bộ dữ liệu
## Loc cac quoc gia voi so luong ca tu vong/10000 ca nhiem <10  va loai nuoc Timor ra khoi du lieu
#df_clean <- df_clean %>% filter(cv_case_10k < 10000)

data_2 <- data_1 %>% filter(death_case <10) %>% 
  filter(location != "Timor")


## Loc lai bo du lieu voi cac cot gom: ten quoc gia, so ca tu vong, so ca nhiem, so luong ca tu vong/10000 ca nhiem

data_clean <- data_2 %>% select(location, total_cv_death, total_cv_cases, death_case)
```

#Xuat du lieu

```{r}
export(data_clean, here("Dataset", "data_clean_Nhi.rds"))
export(data_clean, here("Dataset", "data_clean_Nhi.xlsx"))
```


